src/CleanArchitecture.Presentation/Models/ErrorViewModel.cs
namespace CleanArchitecture.Presentation.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/CleanArchitecture.Presentation/Controllers/Employees/EmployeesCreateController.cs
using CleanArchitecture.Application.Employees.Commands.CreateEmployee;
using CleanArchitecture.Application.Employees.ViewModels;
using CleanArchitecture.Presentation.Resources;
using Microsoft.AspNetCore.Mvc;

namespace CleanArchitecture.Presentation.Controllers.Employees
{
    public class EmployeesCreateController : Controller
    {
        private readonly ICreateEmployeeCommand _createEmployeeCommand;

        public EmployeesCreateController(
            ICreateEmployeeCommand createEmployeeCommand)
        {
            _createEmployeeCommand = createEmployeeCommand;
        }

        [HttpGet(CommonRoutes.EmployeesCreate)]
        public IActionResult Create()
        {
            ViewBag.Title = PageTitles.EmployeesCreate;

            return View();
        }

        [HttpPost(CommonRoutes.EmployeesCreate)]
        public async Task<IActionResult> Create(BaseEmployeeModel model)
        {

            if (!ModelState.IsValid)
                return View(model);

            await _createEmployeeCommand.ExecuteAsync(model);

            return RedirectToAction("Index", "EmployeesList");
        }
    }
}

src/CleanArchitecture.Presentation/Controllers/Employees/EmployeesEditController.cs
using System;
using CleanArchitecture.Application.Employees.Commands.EditEmployee;
using CleanArchitecture.Application.Employees.Queries.GetEmployeeById;
using CleanArchitecture.Application.Employees.ViewModels;
using CleanArchitecture.Presentation.Resources;
using Microsoft.AspNetCore.Mvc;

namespace CleanArchitecture.Presentation.Controllers.Employees
{
    public class EmployeesEditController : Controller
    {
        private readonly IGetEmployeeByIdQuery _getEmployeeByIdQuery;
        private readonly IEditEmployeeCommand _editEmployeeCommand;

        public EmployeesEditController(
            IGetEmployeeByIdQuery getEmployeeByIdQuery,
            IEditEmployeeCommand editEmployeeCommand)
        {
            _getEmployeeByIdQuery = getEmployeeByIdQuery;
            _editEmployeeCommand = editEmployeeCommand;
        }

        [HttpGet(CommonRoutes.EmployeesEdit)]
        public async Task<IActionResult> Edit(long id)
        {
            var model = await _getEmployeeByIdQuery.ExecuteAsync(id);

            if (model is null)
                return NotFound();

            return View(model);
        }

        [HttpPost(CommonRoutes.EmployeesEdit)]
        public async Task<IActionResult> Edit(EmployeeModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            await _editEmployeeCommand.ExecuteAsync(model);

            return RedirectToAction("Index", "EmployeesList");
        }
    }
}

src/CleanArchitecture.Presentation/Controllers/Employees/EmployeesListController.cs
using CleanArchitecture.Application.Employees.Queries.GetEmployeesList;
using CleanArchitecture.Presentation.Resources;
using Microsoft.AspNetCore.Mvc;

namespace CleanArchitecture.Presentation.Controllers.Employees
{
    public class EmployeesListController : Controller
    {
        private readonly IGetEmployeesListQuery _getEmployeesListQuery;

        public EmployeesListController(
            IGetEmployeesListQuery getEmployeesListQuery)
        {
            _getEmployeesListQuery = getEmployeesListQuery;
        }

        [HttpGet(CommonRoutes.EmployeesList)]
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = PageTitles.EmployeesIndex;

            var employees = await _getEmployeesListQuery.ExecuteAsync();

            return View(employees);
        }
    }
}

src/CleanArchitecture.Presentation/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CleanArchitecture.Presentation.Models;
using CleanArchitecture.Presentation.Resources;

namespace CleanArchitecture.Presentation.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [Route(CommonRoutes.Error)]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        var model = new ErrorViewModel
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
        };

        return View(model);
    }

    [Route(CommonRoutes.NotFound)]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult ErrorNotFound()
    {
        var path = HttpContext.Items[HttpContextItems.RequestOrigin] as string;

        if (!string.IsNullOrWhiteSpace(path))
            ViewBag.OriginalPath = string.Concat("at ", path, " ");

        return View();
    }
}

src/CleanArchitecture.Presentation/Controllers/Products/ProductsCreateController.cs
namespace CleanArchitecture.Presentation.Controllers.Products
{
    public class ProductsCreateController
    {
        public ProductsCreateController()
        {
        }
    }
}

src/CleanArchitecture.Presentation/Controllers/Products/ProductsListController.cs
using CleanArchitecture.Application.Products.Queries.GetProductList;
using CleanArchitecture.Presentation.Resources;
using Microsoft.AspNetCore.Mvc;

namespace CleanArchitecture.Presentation.Controllers.Products
{
    public class ProductsListController : Controller
    {
        private readonly IGetProductsListQuery _getProductsListQuery;

        public ProductsListController(
            IGetProductsListQuery getProductsListQuery)
        {
            _getProductsListQuery = getProductsListQuery;
        }

        [HttpGet(CommonRoutes.ProductsList)]
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = PageTitles.ProductsIndex;

            var products = await _getProductsListQuery.ExecuteAsync();

            return View(products);
        }
    }
}

src/CleanArchitecture.Presentation/Views/Employees/Create.cshtml
@using CleanArchitecture.Application.Employees.Commands.CreateEmployee

@model CreateEmployeeModel

<h2>@ViewBag.Title</h2>
<hr>

<form asp-action="Create">
    <div class="row">
        <div class="col-12">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-1 text-md-end">
            <label asp-for="Name" class="control-label text-right"></label>
        </div>
        <div class="col-md-4">
            <input asp-for="Name" class="form-control">
        </div>
        <div class="col-md-7">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

src/CleanArchitecture.Presentation/Views/Employees/Index.cshtml
@using CleanArchitecture.Application.Employees.ViewModels

@model IList<EmployeeModel>

<h2>@ViewBag.Title</h2>
<hr>

<table class="table table-stripped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(x => x[0].Id)
            </th>
            <th>@Html.DisplayNameFor(x => x[0].Name)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count == 0)
        {
            <tr>
                <td colspan="3">
                    There are no employees
                </td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        <a class="btn btn-sm btn-outline-primary"
                           asp-controller="Employees"
                           asp-action="Edit"
                           asp-route-id="@item.Id"
                           role="button">
                            Edit
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                <a class="btn btn-sm btn-outline-primary" asp-controller="Employees" asp-action="Create" role="button">
                    Create
                </a>
            </td>
        </tr>
    </tfoot>
</table>

src/CleanArchitecture.Presentation/Views/EmployeesCreate/Create.cshtml
@using CleanArchitecture.Application.Employees.ViewModels

@model BaseEmployeeModel

<h2>@ViewBag.Title</h2>
<hr>

<form asp-action="Create">
    <div class="row">
        <div class="col-12">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-1 text-md-end">
            <label asp-for="Name" class="control-label text-right"></label>
        </div>
        <div class="col-md-4">
            <input asp-for="Name" class="form-control">
        </div>
        <div class="col-md-7">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

src/CleanArchitecture.Presentation/Views/EmployeesEdit/Edit.cshtml
@using CleanArchitecture.Application.Employees.ViewModels

@model EmployeeModel

<h2>@ViewBag.Title</h2>
<hr>

<form asp-action="Edit">
    <input asp-for="Id" type="hidden">
    <div class="row">
        <div class="col-12">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-1 text-md-end">
            <label asp-for="Name" class="control-label text-right"></label>
        </div>
        <div class="col-md-4">
            <input asp-for="Name" class="form-control">
        </div>
        <div class="col-md-7">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

src/CleanArchitecture.Presentation/Views/EmployeesList/Index.cshtml
@using CleanArchitecture.Application.Employees.ViewModels

@model IList<EmployeeModel>

<h2>@ViewBag.Title</h2>
<hr>

<table class="table table-stripped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(x => x[0].Id)
            </th>
            <th>@Html.DisplayNameFor(x => x[0].Name)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count == 0)
        {
            <tr>
                <td colspan="3">
                    There are no employees
                </td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        <a class="btn btn-sm btn-outline-primary"
                           asp-controller="EmployeesEdit"
                           asp-action="Edit"
                           asp-route-id="@item.Id"
                           role="button">
                            Edit
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                <a class="btn btn-sm btn-outline-primary" asp-controller="EmployeesCreate" asp-action="Create" role="button">
                    Create
                </a>
            </td>
        </tr>
    </tfoot>
</table>

src/CleanArchitecture.Presentation/Views/Home/ErrorNotFound.cshtml
@{
    ViewData["Title"] = "Page Not Found!";
}

<h1 class="text-danger">@ViewData["Title"]</h1>
<h2 class="text-danger">It's not there! Try somewhere else!</h2>

<p>Whatever you were looking for <span>@ViewBag.OriginalPath</span>could not be found!</p>

src/CleanArchitecture.Presentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/CleanArchitecture.Presentation/Views/ProductsList/Index.cshtml
@using CleanArchitecture.Application.Products.ViewModels

@model IList<ProductModel>

<h2>@ViewBag.Title</h2>
<hr>

<table class="table table-stripped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(x => x[0].Id)
            </th>
            <th>@Html.DisplayNameFor(x => x[0].Name)</th>
            <th>@Html.DisplayNameFor(x => x[0].Price)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count == 0)
        {
            <tr>
                <td colspan="4">
                    There are no products
                </td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Price
                    </td>
                    <td>
                        <a class="btn btn-sm btn-outline-primary"
                           asp-controller="ProductsEdit"
                           asp-action="Edit"
                           asp-route-id="@item.Id"
                           role="button">
                            Edit
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4">
                <a class="btn btn-sm btn-outline-primary" asp-controller="ProductsCreate" asp-action="Create" role="button">
                    Create
                </a>
            </td>
        </tr>
    </tfoot>
</table>

src/CleanArchitecture.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CleanArchitecture - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CleanArchitecture.Presentation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CleanArchitecture</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeesList" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductsList" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CleanArchitecture - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>